<?php
use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Framework\View\Element\Template $block */
$data = $block->getData();
$details = $block->getData(TokenUiComponentProviderInterface::COMPONENT_DETAILS);

$optimalCCVaultIndex = -1;

$optimalCCVaultIndex++;



/**
 *@var \Magento\Framework\View\Layout\Interceptor $layout
 */
$layout = $this->getLayout();


$allChildBlocks = $this->getLayout()->getAllBlocks();
?>

<style>
.optimal-saved-item {
    margin-top:10px;
    margin-left:20px;
}
</style>
<div id="optimal-cc-vault-container" style="display:none">
<?php
$vaultIndex = 0;
do {
    $blockKey = "optimal_cc_vault." . $vaultIndex;
    $vaultIndex++;
    if(!isset($allChildBlocks[$blockKey])) {
        break;
    }
    $newBlock = $allChildBlocks[$blockKey];
    $newBlock->setTemplate("Commer_Optimal::form/vault-item.phtml");
    echo $newBlock->toHtml();
}while($vaultIndex<100);
?>
</div>
<script language="javascript">

jQuery("#p_method_optimal_cc_vault").click(function(){
    if(this.checked) {
        jQuery("#optimal-cc-vault-container").show();
    }
});
//jQuery("#p_method_optimal_cc_vault").trigger("click");
</script>